# Generated by Django 5.2.6 on 2025-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('segment', models.CharField(choices=[('VIP', 'VIP'), ('REGULAR', 'Regular'), ('BLOCKED', 'Blocked')], default='REGULAR', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this customer was first added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this customer record was updated.')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
